#!/usr/bin/env node
/**
 * Builds the general German noun dictionary (`linguistic/data/germanNouns.tsv`) from german-nouns
 * (de.wiktionary, CC BY-SA 4.0). The source is pinned to a commit so every run gives the same file.
 *
 * Line format: lemma \t genders \t flags \t singular forms \t plural forms
 *   genders — comma list (m,f,n), empty for pluralia tantum; flags — comma list: "w=<form>" weak masculine
 *   with its accusative/dative form, "a" adjectival declension; forms — comma lists, "~x" means lemma + "x";
 *   the first plural form is the nominative plural.
 *
 * Usage: node scripts/lexicon/buildGermanNouns.mjs [path/to/nouns.csv]
 */
import fs from 'node:fs';

const SOURCE_COMMIT = 'da71a2bc519b952b28c9b0b80971cff6efb508f6';
const SOURCE_URL = `https://raw.githubusercontent.com/gambolputty/german-nouns/${SOURCE_COMMIT}/german_nouns/nouns.csv`;
const OUTPUT = new URL('../../src/services/schreiben/linguistic/data/germanNouns.tsv', import.meta.url);
const CASES = ['nominativ', 'genitiv', 'dativ', 'akkusativ'];

const HEADER = [
  '# German noun dictionary generated by scripts/lexicon/buildGermanNouns.mjs — do not edit by hand.',
  `# Source: german-nouns by Gregor Weichbrodt, ${SOURCE_URL}`,
  '# Data from Wiktionary (de.wiktionary.org), its authors: https://de.wiktionary.org',
  '# License: CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/). Modified: selected columns, compact form notation.',
];

function parseCsvLine(line) {
  const fields = [];
  let field = '';
  let quoted = false;
  for (const ch of line) {
    if (ch === '"') quoted = !quoted;
    else if (ch === ',' && !quoted) { fields.push(field); field = ''; }
    else field += ch;
  }
  fields.push(field);
  return fields;
}

/** Column indexes per number: every case column, incl. variants (*, 1–4) and adjectival (stark/schwach/gemischt). */
function indexColumns(header) {
  const byNumber = { singular: [], plural: [] };
  header.forEach((name, i) => {
    const [kase, number] = name.split(' ');
    if (CASES.includes(kase) && byNumber[number?.replace('*', '')]) byNumber[number.replace('*', '')].push({ i, kase });
  });
  return { ...byNumber, genus: header.map((n, i) => (/^genus( \d)?$/.test(n) ? i : -1)).filter((i) => i >= 0) };
}

function formsOf(row, columns, kase = null) {
  return [...new Set(columns.filter((c) => !kase || c.kase === kase).map((c) => row[c.i]).filter(Boolean))];
}

function toRecord(row, columns) {
  const lemma = row[0];
  const plural = [...new Set([...formsOf(row, columns.plural, 'nominativ'), ...formsOf(row, columns.plural)])];
  // The archaic dative -e ("dem Termine") is spelled like the plural "Termine": a singular form found only in the
  // dative is dropped when the plural has it. Any other shared form stays singular ("der Lehrer", "den Kunden").
  const nonDative = ['nominativ', 'genitiv', 'akkusativ'].flatMap((kase) => formsOf(row, columns.singular, kase));
  const singular = formsOf(row, columns.singular).filter((f) => nonDative.includes(f) || !plural.includes(f));
  if (!/^[A-ZÄÖÜ]/.test(lemma) || !/Substantiv/.test(row[1]) || /Gebundenes Lexem/.test(row[1])) return null;
  if (singular.length === 0 && plural.length === 0) return null;
  const genders = [...new Set(columns.genus.map((i) => row[i]).filter((g) => /^[mfn]$/.test(g)))];
  const nominative = formsOf(row, columns.singular, 'nominativ')[0];
  const accusative = formsOf(row, columns.singular, 'akkusativ');
  const dative = formsOf(row, columns.singular, 'dativ');
  const isWeak = genders.join() === 'm' && accusative.length > 0 && accusative.join() === dative.join()
    && accusative.every((f) => f !== nominative && /e?n$/.test(f));
  const flags = [isWeak && `w=${compact(lemma, [accusative[0]])}`, /adjektivische Deklination/.test(row[1]) && 'a'].filter(Boolean);
  return { lemma, genders, flags: flags.join(','), singular, plural };
}

function compact(lemma, forms) {
  return forms.map((f) => (f !== lemma && f.startsWith(lemma) ? `~${f.slice(lemma.length)}` : f)).join(',');
}
const toLine = (r) => [r.lemma, r.genders.join(','), r.flags, compact(r.lemma, r.singular), compact(r.lemma, r.plural)].join('\t');

async function readSource(localPath) {
  if (localPath) return fs.readFileSync(localPath, 'utf8');
  const response = await fetch(SOURCE_URL);
  if (!response.ok) throw new Error(`Download failed: ${response.status} ${SOURCE_URL}`);
  return response.text();
}

async function main() {
  const [headerLine, ...lines] = (await readSource(process.argv[2])).split(/\r?\n/);
  const columns = indexColumns(parseCsvLine(headerLine));
  const records = lines.map((l) => toRecord(parseCsvLine(l), columns)).filter(Boolean);
  const unique = [...new Map(records.map((r) => [toLine(r), r])).values()];
  fs.writeFileSync(OUTPUT, `${[...HEADER, ...unique.map(toLine)].join('\n')}\n`);
  console.log(`germanNouns.tsv: ${unique.length} lemmas`);
}

main().catch((error) => { console.error(error.message); process.exit(1); });
