#!/usr/bin/env node
/**
 * Builds the general German verb dictionary (`linguistic/data/germanVerbs.tsv`) from german-verbs-database
 * (de.wiktionary conjugation tables, CC BY-SA 4.0). The source is pinned to a commit so every run gives the same file.
 *
 * Line format: infinitive \t separable prefix \t ich \t du \t er/sie/es \t Präteritum ich \t Partizip II
 *   every form column is a comma list of variants; a separable verb keeps only its infinitive and participle
 *   (its finite forms are the base verb's: "rufe … an" is "rufen" plus the prefix), its prefix column names the prefix.
 *   The "ihr" and plural forms follow from the infinitive (the source's imperative plural is archaic for "wissen": "wisset").
 *
 * Usage: node scripts/lexicon/buildGermanVerbs.mjs [path/to/verbs.csv]
 */
import fs from 'node:fs';

const SOURCE_COMMIT = '11771d4a2c50be92fa5000fded8d3287dee259f0';
const SOURCE_URL = `https://raw.githubusercontent.com/viorelsfetea/german-verbs-database/${SOURCE_COMMIT}/output/verbs.csv`;
const OUTPUT = new URL('../../src/services/schreiben/linguistic/data/germanVerbs.tsv', import.meta.url);
const COLUMNS = { infinitive: 0, ich: 1, du: 2, er: 3, past: 4, participle: 5 };

const HEADER = [
  '# German verb dictionary generated by scripts/lexicon/buildGermanVerbs.mjs — do not edit by hand.',
  `# Source: german-verbs-database by Viorel Sfetea, ${SOURCE_URL}`,
  '# Data from Wiktionary (de.wiktionary.org), its authors: https://de.wiktionary.org',
  '# License: CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/). Modified: selected columns, cleaned variants.',
];

/** CSV rows; quoted fields may hold commas and line breaks. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"' && text[i + 1] === '"') { field += '"'; i++; } else if (ch === '"') quoted = false; else field += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { row.push(field); field = ''; } else if (ch === '\n') { row.push(field); rows.push(row); row = []; field = ''; } else if (ch !== '\r') field += ch;
  }
  if (field || row.length) rows.push([...row, field]);
  return rows;
}

/** Variants of one table cell: markup and notes removed, only word forms kept. */
function variants(cell = '') {
  const clean = cell.replace(/<!--[\s\S]*?-->/g, '').replace(/<[^>]+>/g, '').replace(/[()]/g, '');
  return [...new Set(clean.split(/[,;/\n]/).map((v) => v.trim()).filter((v) => /^[a-zäöüß]+( [a-zäöüß]+)?$/.test(v)))];
}

function toRecord(row) {
  const [infinitive] = variants(row[COLUMNS.infinitive]);
  if (!infinitive || infinitive.includes(' ')) return null;
  const [firstPerson = ''] = variants(row[COLUMNS.ich]);
  const prefix = firstPerson.includes(' ') ? firstPerson.split(' ')[1] : '';
  if (prefix && !infinitive.startsWith(prefix)) return null;
  const finite = (column) => (prefix ? [] : variants(row[COLUMNS[column]]).filter((v) => !v.includes(' ')));
  return [infinitive, prefix, ...['ich', 'du', 'er', 'past'].map((c) => finite(c).join(',')),
    variants(row[COLUMNS.participle]).filter((v) => !v.includes(' ')).join(',')];
}

async function readSource(localPath) {
  if (localPath) return fs.readFileSync(localPath, 'utf8');
  const response = await fetch(SOURCE_URL);
  if (!response.ok) throw new Error(`Download failed: ${response.status} ${SOURCE_URL}`);
  return response.text();
}

async function main() {
  const [, ...rows] = parseCsv(await readSource(process.argv[2]));
  const lines = [...new Set(rows.map(toRecord).filter(Boolean).map((r) => r.join('\t')))];
  fs.writeFileSync(OUTPUT, `${[...HEADER, ...lines].join('\n')}\n`);
  console.log(`germanVerbs.tsv: ${lines.length} verbs`);
}

main().catch((error) => { console.error(error.message); process.exit(1); });
